stages:
  - build
  - lint


# build:
#   stage: build
#   image: python
#   script:
#     - pip install poetry
#     - poetry install --no-root
#   artifacts:
#     paths:
#       - "build/"



lint:
  stage: lint
  # needs:
  #   - build
  image: python:3.11
  script:
    - pip install poetry
    - poetry install --no-root
    - poetry run pylint ./* --output-format=json:lint.json,colorized --exit-zero
    - poetry run python ./pylint-ci.py lint.json gitlab.json
    - ls -la
  artifacts:
    name: "PyLint Atr name"
    reports:
      codequality: /gitlab.json
    expire_in: 7days
