stages:
  - build
  - lint


build:
  stage: build
  image: python
  script:
    - pip install poetry
    - poetry shell
    - poetry install
  artifacts:
    paths:
      - "build/"



lint:
  stage: lint
  image: python
  script:
    - pylint ./build/* --output-format=json:lint.json,colorized
    - python ./build/pylint-ci.py lint.json gitlab.json
  artifacts:
    name: "PyLint Atr name"
    reports:
      codequality: /gitlab.json
    expire_in: 7days
