stages:
  - build
  - lint


build:
  stage: build
  image: python
  script:
    - pip install poetry
    - poetry install --no-root
  artifacts:
    paths:
      - build/*



lint:
  stage: lint
  image: python
  script:
    - poetry run pylint ./build/* --output-format=json:lint.json,colorized
    - poetry run python ./build/pylint-ci.py lint.json gitlab.json
  artifacts:
    name: "PyLint Atr name"
    reports:
      codequality: /gitlab.json
    expire_in: 7days
