[tool.poetry]
name = "flask-server"
version = "0.1.0"
description = ""
authors = ["dianamatkava"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pylint = "^3.1.0"
environs = "^11.0.0"
flask = "^3.0.2"
flask-migrate = "^4.0.7"
flask-sqlalchemy = "^3.1.1"
flask-admin = "^1.6.1"
flask-login = "^0.6.3"
flask-serialize = "^2.1.3"

[tool.poetry.group.pylint.dependencies]
pylint = "^3.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
